=== GCS-SSC/gcforms-localtest/platform-forms-client/lib/middleware/schemas/templates.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "id": "https://forms-formulaires.alpha.canada.ca/",
  "type": "object",
  "title": "GC Forms Schema - Alpha",
  "description": "A schema to define a Forms configuration.",
  "default": {},
  "examples": [
    {
      "titleEn": "",
      "titleFr": "",
      "introduction": {},
      "privacyPolicy": {},
      "confirmation": {},
      "layout": [],
      "elements": [],
      "startPage": {},
      "brand": {}
    }
  ],
  "properties": {
    "titleEn": {
      "description": "The displayed title of the form to the user in English",
      "id": "#/properties/titleEn",
      "type": "string"
    },
    "titleFr": {
      "description": "The displayed title of the form to the user in French",
      "id": "#/properties/titleFr",
      "type": "string"
    },
    "introduction": {
      "description": "Form introduction",
      "id": "#/properties/introduction",
      "type": "object",
      "properties": {
        "descriptionEn": {
          "type": "string"
        },
        "descriptionFr": {
          "type": "string"
        }
      }
    },
    "privacyPolicy": {
      "description": "Form privacy policy",
      "id": "#/properties/privacyPolicy",
      "type": "object",
      "properties": {
        "descriptionEn": {
          "type": "string"
        },
        "descriptionFr": {
          "type": "string"
        }
      }
    },
    "confirmation": {
      "description": "Content that will be displayed after a form is submitted.",
      "id": "#/properties/confirmation",
      "type": "object",
      "properties": {
        "descriptionEn": {
          "type": "string"
        },
        "descriptionFr": {
          "type": "string"
        },
        "referrerUrlEn": {
          "type": "string"
        },
        "referrerUrlFr": {
          "type": "string"
        }
      }
    },
    "layout": {
      "description": "A list of element IDs that determines the order or elements in the form.",
      "type": "array",
      "items": {
        "type": "number"
      },
      "uniqueItems": true,
      "examples": [[2, 3, 4, 6, 9, 5]]
    },
    "groups": {
      "type": "object",
      "properties": {
        "name": {
          "description": "The name of the group.",
          "type": "string"
        },
        "titleEn": {
          "description": "The title of the group in English.",
          "type": "string"
        },
        "titleFr": {
          "description": "The title of the group in French.",
          "type": "string"
        },
        "nextAction": {
          "description": "The next action to take i.e. next group or submit.",
          "type": "string"
        },
        "elements": {
          "description": "A list of elements contained within the form group.",
          "type": "array"
        }
      }
    },
    "groupsLayout": {
      "description": "A list of group IDs that determines the order of the groups in the form.",
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true,
      "examples": [["one", "two"]]
    },
    "elements": {
      "description": "A list of elements contained within the form.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/element"
      },
      "examples": [
        {
          "id": 1,
          "type": "richText",
          "properties": {
            "validation": {
              "required": false
            },
            "descriptionEn": "#### Section 1: Nomination Category",
            "descriptionFr": "#### Section 1: Catégorie de la nomination"
          }
        },
        {
          "id": 2,
          "uuid": "12345678-1234-1234-1234-123456789012",
          "type": "radio",
          "properties": {
            "questionId": "my_custom_id",
            "tags": ["radio", "nomination"],
            "choices": [
              {
                "en": "Team nomination",
                "fr": "Mise en candidature d’une équipe"
              },
              {
                "en": "Individual Nomination",
                "fr": "Mise en candidature d’une personne"
              }
            ],
            "titleEn": "Is this a Team or Individual Nomination?",
            "titleFr": "Is this a Team or Individual Nomination?",
            "validation": {
              "required": true
            },
            "descriptionEn": "",
            "descriptionFr": ""
          }
        }
      ]
    },
    "brand": {
      "type": "object",
      "properties": {
        "name": {
          "description": "The brand name.",
          "type": "string"
        },
        "urlEn": {
          "description": "URL for English version of the site.",
          "type": "string"
        },
        "urlFr": {
          "description": "URL for a French version of the site.",
          "type": "string"
        },
        "logoEn": {
          "description": "English logo path.",
          "type": "string"
        },
        "logoFr": {
          "description": "French logo path.",
          "type": "string"
        },
        "logoTitleEn": {
          "description": "logo title.",
          "type": "string"
        },
        "logoTitleFr": {
          "description": "logo title.",
          "type": "string"
        },
        "disableGCBranding": {
          "description": "If set to true, GC branding will not be rendered in the footer.",
          "type": "boolean"
        }
      }
    },
    "lastGeneratedElementId": {
      "description": "The last generated element id",
      "type": "number"
    }
  },
  "required": ["titleEn", "titleFr", "privacyPolicy", "confirmation", "layout", "elements"],
  "additionalProperties": false,
  "definitions": {
    "element": {
      "type": "object",
      "properties": {
        "id": {
          "description": "The unique id for the object",
          "type": "integer",
          "minimum": 1
        },
        "uuid": {
          "description": "A unique id for the object (future use)",
          "type": "string",
          "format": "uuid"
        },
        "type": {
          "type": "string",
          "enum": [
            "textField",
            "textArea",
            "dropdown",
            "radio",
            "checkbox",
            "fileInput",
            "dynamicRow",
            "richText",
            "attestation",
            "combobox",
            "addressComplete",
            "formattedDate",
            "numberInput"
          ]
        },
        "properties": {
          "type": "object",
          "properties": {
            "questionId": {
              "description": "A user-defined unique id for the question",
              "type": "string"
            },
            "tags": {
              "description": "A list of tags that can be used to group elements together.",
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "titleEn": {
              "description": "Input label in English",
              "type": "string"
            },
            "titleFr": {
              "description": "Input label in French",
              "type": "string"
            },
            "placeholderEn": {
              "description": "Text that will appear in the text input field as a placeholder in English",
              "type": "string"
            },
            "placeholderFr": {
              "description": "Text that will appear in the text input field as a placeholder in French",
              "type": "string"
            },
            "descriptionEn": {
              "description": "Secondary paragraph/text of a question or element that provides additional context beyond the label in English",
              "type": "string"
            },
            "descriptionFr": {
              "description": "Secondary paragraph/text of a question or element that provides additional context beyond the label in French",
              "type": "string"
            },
            "dynamicRow": {
              "type": "object",
              "properties": {
                "rowTitleEn": {
                  "type": "string",
                  "description": "The title of the row in English"
                },
                "rowTitleFr": {
                  "type": "string",
                  "description": "The title of the row in French"
                },
                "addButtonTextEn": {
                  "type": "string",
                  "description": "Text for the add button in English"
                },
                "removeButtonTextEn": {
                  "type": "string",
                  "description": "Text for the remove button in English"
                },
                "addButtonTextFr": {
                  "type": "string",
                  "description": "Text for the add button in French"
                },
                "removeButtonTextFr": {
                  "type": "string",
                  "description": "Text for the remove button in French"
                }
              }
            },
            "choices": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "en": {
                    "description": "English choice",
                    "type": "string"
                  },
                  "fr": {
                    "description": "French choice",
                    "type": "string"
                  }
                }
              }
            },
            "sortOrder": {
              "type": "string",
              "description": "Controls how choices are displayed",
              "enum": ["none", "ascending", "descending"],
              "default": "none"
            },
            "managedChoices": {
              "type": ["array", "string"],
              "description": "The name of the data file(s) containing the choices for this element."
            },
            "conditionalRules": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "choiceId": {
                    "description": "The id of the element that will trigger the conditional rule",
                    "type": "string",
                    "minimum": 1
                  }
                }
              }
            },
            "maxNumberOfRows": {
              "type": "integer",
              "minimum": 1
            },
            "strictValue": {
              "description": "If set to true, the element will only accept values that are in the choices list.",
              "type": "boolean"
            },
            "allowNegativeNumbers": {
              "description": "If set to true, the number input will allow negative numbers.",
              "type": "boolean"
            },
            "stepCount": {
              "description": "The number of decimals allowed for a number input.",
              "type": "integer",
              "minimum": 0
            },
            "currencyCode": {
              "description": "The ISO 4217 currency code used to format the number input as currency (e.g. CAD, USD).",
              "type": "string"
            },
            "useThousandsSeparator": {
              "description": "If set to true, the number input will format numbers with a thousands separator.",
              "type": "boolean"
            },
            "validation": {
              "type": "object",
              "properties": {
                "required": {
                  "type": "boolean"
                },
                "type": {
                  "type": "string",
                  "enum": [
                    "email",
                    "alphanumeric",
                    "text",
                    "name",
                    "number",
                    "phone",
                    "date",
                    "custom"
                  ]
                },
                "regex": {
                  "type": "string"
                },
                "maxLength": {
                  "description": "The maximum number of characters that can be entered in a textinput or textarea.",
                  "type": "integer",
                  "minimum": 1
                },
                "minValue": {
                  "description": "The minimum allowed numeric value for a number input.",
                  "type": "number"
                },
                "maxValue": {
                  "description": "The maximum allowed numeric value for a number input.",
                  "type": "number"
                },
                "minDigits": {
                  "description": "The minimum number of digits required for a number input.",
                  "type": "integer",
                  "minimum": 1
                },
                "maxDigits": {
                  "description": "The maximum number of digits allowed for a number input.",
                  "type": "integer",
                  "minimum": 1
                },
                "descriptionEn": {
                  "type": "string"
                },
                "descriptionFr": {
                  "type": "string"
                },
                "all": {
                  "description": "Used only for checkboxes, ignored on other elements. When set to true, this will require that all checkboxes be selected. Used typically for the attestation section.",
                  "type": "boolean"
                }
              },
              "examples": [
                {
                  "validation": {
                    "required": true,
                    "type": "email",
                    "descriptionEn": "Enter a valid email address.",
                    "descriptionFr": "Veuillez entrer une adresse courriel valide."
                  }
                },
                {
                  "validation": {
                    "required": false,
                    "type": "alphanumeric",
                    "descriptionEn": "Please enter your home street address.",
                    "descriptionFr": "Veuillez entrer votre adresse postale."
                  }
                }
              ]
            },
            "subElements": {
              "description": "A list of subElements contained within a dynamicRow",
              "type": "array",
              "items": {
                "$ref": "#/definitions/element"
              }
            }
          }
        }
      },
      "required": ["id", "type", "properties"]
    }
  }
}

=== GCS-SSC/gcforms-localtest/platform-forms-client/__fixtures__/navigationFocus.json
{
  "titleEn": "Navigation Focus",
  "titleFr": "[FR]Navigation Focus",
  "introduction": {
    "descriptionEn": "",
    "descriptionFr": ""
  },
  "privacyPolicy": {
    "descriptionEn": "p",
    "descriptionFr": "[FR]p"
  },
  "confirmation": {
    "descriptionEn": "c",
    "descriptionFr": "c",
    "referrerUrlEn": "",
    "referrerUrlFr": ""
  },
  "layout": [1, 2, 3],
  "elements": [
    {
      "id": 3,
      "type": "textField",
      "properties": {
        "subElements": [],
        "choices": [
          {
            "en": "",
            "fr": ""
          }
        ],
        "titleEn": "QB",
        "titleFr": "[FR]QB",
        "validation": {
          "required": true
        },
        "descriptionEn": "",
        "descriptionFr": "",
        "placeholderEn": "",
        "placeholderFr": ""
      },
      "uuid": "97d37bc1-a464-4514-9818-6dd1a416c6f2"
    },
    {
      "id": 2,
      "type": "textField",
      "properties": {
        "subElements": [],
        "choices": [
          {
            "en": "",
            "fr": ""
          }
        ],
        "titleEn": "QA",
        "titleFr": "[FR]QA",
        "validation": {
          "required": true
        },
        "descriptionEn": "",
        "descriptionFr": "",
        "placeholderEn": "",
        "placeholderFr": ""
      },
      "uuid": "ec3ad6f9-29a2-48da-83e7-d93b43eae478"
    },
    {
      "id": 1,
      "type": "radio",
      "properties": {
        "subElements": [],
        "choices": [
          {
            "en": "A",
            "fr": "[FR]A"
          },
          {
            "en": "B",
            "fr": "[FR]B"
          }
        ],
        "titleEn": "Page?",
        "titleFr": "[FR]Page?",
        "validation": {
          "required": true
        },
        "descriptionEn": "",
        "descriptionFr": "",
        "placeholderEn": "",
        "placeholderFr": ""
      },
      "uuid": "f86151dd-d246-4f44-9156-6058ab63229d"
    }
  ],
  "groups": {
    "start": {
      "name": "Start",
      "titleEn": "Start page",
      "titleFr": "Start page",
      "elements": ["1"],
      "nextAction": [
        {
          "groupId": "bd4c615d-fef5-4a38-b1f0-c73954803867",
          "choiceId": "1.0"
        },
        {
          "groupId": "60756820-065f-42fd-9d8d-198770a46c7b",
          "choiceId": "1.1"
        }
      ],
      "autoFlow": false
    },
    "bd4c615d-fef5-4a38-b1f0-c73954803867": {
      "name": "A",
      "elements": ["2"],
      "titleEn": "A",
      "titleFr": "[FR]A",
      "nextAction": "review",
      "autoFlow": false
    },
    "60756820-065f-42fd-9d8d-198770a46c7b": {
      "name": "B",
      "elements": ["3"],
      "titleEn": "B",
      "titleFr": "[FR]B",
      "nextAction": "review",
      "autoFlow": true
    },
    "review": {
      "name": "Review",
      "titleEn": "End (Review page and Confirmation)",
      "titleFr": "End (Review page and Confirmation)",
      "elements": [],
      "nextAction": "end"
    },
    "end": {
      "name": "End",
      "titleEn": "Confirmation page",
      "titleFr": "Confirmation page",
      "elements": []
    }
  },
  "groupsLayout": ["bd4c615d-fef5-4a38-b1f0-c73954803867", "60756820-065f-42fd-9d8d-198770a46c7b"],
  "lastGeneratedElementId": 3
}
